In [1]:
import numpy as np
import matplotlib.pyplot as mpl
import pandas as pd

In [2]:
ds = pd.read_csv("DataWisata.csv")

x = ds.iloc[:, [2,4]].values
y = ds.iloc[:, [0,3]].values

In [3]:
print(np.array(x))

[['TIJA Ancol*' 19261212]
 ['Taman Mini Indonesia Indah*' 5702950]
 ['T. Marga Satwa Ragunan*' 5363883]
 ['Monumen Nasional' 1850471]
 ['Museum Nasional' 256825]
 ['Museum Satria Mandala' 36144]
 ['Museum Sejarah Jakarta' 783908]
 ['Museum Tekstil' 44761]
 ['Museum Bahari' 31149]
 ['M. Seni Rupa dan Keramik' 202887]
 ['Museum Wayang' 373521]
 ["Museum Joang '45" 15465]
 ['Taman Arkeologi P.Onrust' 68667]
 ['Pel. Sunda Kelapa' 55326]
 ['Kepulauan Seribu ' 842762]
 ['PBB Setu Babakan ' 517805]
 ['Museum Prasasti ' 10268]
 ['TIJA Ancol*' 17575914]
 ['Taman Mini Indonesia Indah*' 6004718]
 ['T. Marga Satwa Ragunan*' 5455788]
 ['Monumen Nasional' 1945747]
 ['Museum Nasional' 263171]
 ['Museum Satria Mandala' 11693]
 ['Museum Sejarah Jakarta' 812668]
 ['Museum Tekstil' 41805]
 ['Museum Bahari' 24774]
 ['M. Seni Rupa dan Keramik' 190569]
 ['Museum Wayang' 372885]
 ["Museum Joang '45" 18711]
 ['Taman Arkeologi P.Onrust' 65448]
 ['Pel. Sunda Kelapa' 45653]
 ['Kepulauan Seribu ' 662420]
 ['PBB S

In [4]:
print(y)

[[2017 'Jakarta Utara']
 [2017 'Jakarta Timur']
 [2017 'Jakarta Selatan']
 [2017 'Jakarta Pusat']
 [2017 'Jakarta Pusat']
 [2017 'Jakarta Selatan']
 [2017 'Jakarta Barat']
 [2017 'Jakarta Barat']
 [2017 'Jakarta Utara']
 [2017 'Jakarta Barat']
 [2017 'Jakarta Barat']
 [2017 'Jakarta Pusat']
 [2017 'Jakarta Utara']
 [2017 'Jakarta Utara']
 [2017 'Jakarta Utara']
 [2017 'Jakarta Selatan']
 [2017 'Jakarta Pusat']
 [2018 'Jakarta Utara']
 [2018 'Jakarta Timur']
 [2018 'Jakarta Selatan']
 [2018 'Jakarta Pusat']
 [2018 'Jakarta Pusat']
 [2018 'Jakarta Selatan']
 [2018 'Jakarta Barat']
 [2018 'Jakarta Barat']
 [2018 'Jakarta Utara']
 [2018 'Jakarta Barat']
 [2018 'Jakarta Barat']
 [2018 'Jakarta Pusat']
 [2018 'Jakarta Utara']
 [2018 'Jakarta Utara']
 [2018 'Jakarta Utara']
 [2018 'Jakarta Selatan']
 [2018 'Jakarta Pusat']
 [2019 'Jakarta Utara']
 [2019 'Jakarta Timur']
 [2019 'Jakarta Selatan']
 [2019 'Jakarta Pusat']
 [2019 'Jakarta Pusat']
 [2019 'Jakarta Selatan']
 [2019 'Jakarta Barat']


In [10]:
from sklearn.compose import ColumnTransformer as CT
from sklearn.preprocessing import OneHotEncoder as OHE
ct = CT(transformers=[('encoder', OHE(sparse=True), [0])], remainder='passthrough') #penamanaan "tes" bebas
x = np.array(ct.fit_transform(x))                            

In [13]:
print(x)

[[1.0 0.0 0.0 ... 0.0 0.0 19261212]
 [1.0 0.0 0.0 ... 0.0 1.0 5702950]
 [1.0 0.0 0.0 ... 0.0 0.0 5363883]
 ...
 [0.0 1.0 0.0 ... 0.0 0.0 597526]
 [1.0 0.0 0.0 ... 0.0 0.0 471910]
 [1.0 0.0 0.0 ... 0.0 0.0 10178]]


In [36]:
from sklearn.preprocessing import LabelEncoder as LE
lbl_encode = LE()
y[:, 0] = lbl_encode.fit_transform(y[:, 0])

In [37]:
print(y)

[[0 4]
 [0 3]
 [0 2]
 [0 1]
 [0 1]
 [0 2]
 [0 0]
 [0 0]
 [0 4]
 [0 0]
 [0 0]
 [0 1]
 [0 4]
 [0 4]
 [0 4]
 [0 2]
 [0 1]
 [1 4]
 [1 3]
 [1 2]
 [1 1]
 [1 1]
 [1 2]
 [1 0]
 [1 0]
 [1 4]
 [1 0]
 [1 0]
 [1 1]
 [1 4]
 [1 4]
 [1 4]
 [1 2]
 [1 1]
 [2 4]
 [2 3]
 [2 2]
 [2 1]
 [2 1]
 [2 2]
 [2 0]
 [2 0]
 [2 4]
 [2 0]
 [2 0]
 [2 1]
 [2 4]
 [2 4]
 [2 4]
 [2 2]
 [2 1]]


In [54]:
from sklearn.model_selection import train_test_split as tts
x_train, x_tes, y_train, y_tes = tts(x,y, test_size = 0.2, random_state = 1)

In [53]:
print(x_train)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 256825]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  0.0 0.0 10359661]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 842762]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 662420]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 0.0 373521]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 18711]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 18545]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 1.0 5064814]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 1.0 6004718]
 [1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 1945747]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0

In [40]:
print(x_tes)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 11693]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 0.0 5363883]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 471910]
 [1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 190569]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 12356]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 0.0 312081]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 0.0 45653]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 10178]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 437766]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 0.0 372885]
 [1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0

In [41]:
print(y_train)

[[1 4]
 [2 4]
 [2 0]
 [2 2]
 [1 1]
 [2 0]
 [2 1]
 [1 2]
 [1 0]
 [0 4]
 [2 4]
 [1 4]
 [2 4]
 [2 2]
 [1 0]
 [0 1]
 [2 4]
 [0 4]
 [1 4]
 [0 0]
 [1 1]
 [2 1]
 [2 3]
 [1 3]
 [1 1]
 [1 4]
 [0 0]
 [0 0]
 [2 4]
 [0 3]
 [0 1]
 [0 4]
 [0 2]
 [0 2]
 [0 1]
 [0 0]
 [0 4]
 [0 4]
 [2 0]
 [2 1]]


In [42]:
print(y_tes)

[[1 2]
 [0 2]
 [2 2]
 [1 0]
 [1 1]
 [2 0]
 [1 4]
 [2 1]
 [1 2]
 [1 0]
 [0 1]]


In [55]:
from sklearn.preprocessing import StandardScaler as SS
sc = SS()
x_train[:, -1:] = sc.fit_transform(x_train[:, -1:])
x_tes[:, -1:] = sc.transform(x_tes[:, -1:])

In [56]:
print(x_train)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  1.0 0.0 -0.5019010323237114]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 0.0 -0.5091242986914898]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 -0.5086035710972802]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 -0.5124657775387963]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 -0.4593556512865562]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 -0.36179776686476106]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 -0.4580286566280889]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 0.0 0.6579744966730114]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 -0.506988454848463]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.

In [57]:
print(x_tes)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 -0.5134678553926122]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 0.0 0.6381986828110947]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 -0.41443988381228797]
 [1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 -0.4749779094662295]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 -0.5133251932459341]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 0.0 -0.44883135928953377]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 0.0 -0.5061604549383313]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 -0.5137938480807228]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 -0.4217868767778642]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 